fix: remove nonexistent uart.request_wake_loop_on_rx() call
uart.request_wake_loop_on_rx() does not exist in esphome.components.uart
and causes an AttributeError on ESPHome 2026.3.0+:

  AttributeError: module \esphome.components.uart\' has no attribute \request_wake_loop_on_rx\'